# Auto-generated using compose2nix v0.3.2-pre. Edited.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Create persistent directory for postgres data
  systemd.tmpfiles.rules = [
    "d /srv/stump/config 0750 docker docker -"
  ];

  # Containers
  virtualisation.oci-containers.containers."stump" = {
    image = "aaronleopold/stump:latest";
    environment = {
      # UIDs from the host "docker" user/group. Make sure the host configuration includes users/docker.nix
      "PGID" = "131";
      "PUID" = "990";
    };
    volumes = [
      "/data/books:/data:rw"
      "/srv/stump/config:/config:rw"
    ];
    ports = [
      "10801:10801/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=stump"
      "--network=stump-server_default"
    ];
  };
  systemd.services."docker-stump" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-stump-server_default.service"
    ];
    requires = [
      "docker-network-stump-server_default.service"
    ];
    partOf = [
      "docker-compose-stump-server-root.target"
    ];
    wantedBy = [
      "docker-compose-stump-server-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-stump-server_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f stump-server_default";
    };
    script = ''
      docker network inspect stump-server_default || docker network create stump-server_default
    '';
    partOf = [ "docker-compose-stump-server-root.target" ];
    wantedBy = [ "docker-compose-stump-server-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-stump-server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
